// Generates public/firebase-messaging-sw.js at build time.
// Runs before `next build` so the static export can include it.
// All Firebase vars are NEXT_PUBLIC_* — safe to bake in at build time.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Parse .env.local manually — this script runs before Next.js, which normally
// loads it automatically. CI environments set vars directly, so this is a no-op there.
const envPath = resolve(root, '.env.local');
if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

const firebaseConfig = {
  apiKey:            process.env.NEXT_PUBLIC_FIREBASE_API_KEY             ?? '',
  authDomain:        process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN         ?? '',
  projectId:         process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID          ?? '',
  storageBucket:     process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET      ?? '',
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? '',
  appId:             process.env.NEXT_PUBLIC_FIREBASE_APP_ID              ?? '',
};

const firebaseConfigured = !!(firebaseConfig.apiKey && firebaseConfig.projectId);
const FIREBASE_VERSION = '10.7.1';
const CDN = `https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}`;

const swContent = `\
// HabitFlow — unified service worker (offline caching + Firebase Cloud Messaging)
// Generated by scripts/generate-sw.mjs at build time — do not edit directly.
// Registered with scope '/' via the Service-Worker-Allowed header.

const CACHE_VERSION = 'v4';
const STATIC_CACHE  = 'habitflow-static-'  + CACHE_VERSION;
const IMAGE_CACHE   = 'habitflow-images-'  + CACHE_VERSION;
const DYNAMIC_CACHE = 'habitflow-dynamic-' + CACHE_VERSION;
const IS_DEV_HOST =
  self.location.hostname === 'localhost' ||
  self.location.hostname === '127.0.0.1' ||
  self.location.hostname === '0.0.0.0' ||
  self.location.hostname.startsWith('192.168.') ||
  self.location.hostname.startsWith('10.') ||
  /^172\\.(1[6-9]|2\\d|3[0-1])\\./.test(self.location.hostname);

async function unregisterDevServiceWorker() {
  const keys = await caches.keys();
  await Promise.all(
    keys
      .filter((key) => key.startsWith('habitflow-'))
      .map((key) => caches.delete(key))
  );
  await self.registration.unregister();
  const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
  await Promise.all(clients.map((client) => client.navigate(client.url)));
}

if (IS_DEV_HOST) {
  self.addEventListener('install', (event) => {
    self.skipWaiting();
    event.waitUntil(unregisterDevServiceWorker());
  });

  self.addEventListener('activate', (event) => {
    event.waitUntil(unregisterDevServiceWorker());
  });

  self.addEventListener('fetch', () => {});
} else {

const PASSTHROUGH_SUBSTRINGS = [
  'convex.cloud',
  'convex.site',
  'clerk.accounts.dev',
  'clerk.com',
  'accounts.tryhabitflow.com',
  '/__clerk',
  '/api/',
  '/_next/webpack-hmr',
  '_rsc=',
];

const USER_PAGE_PREFIXES = [
  '/dashboard',
  '/profile',
  '/settings',
  '/habits',
  '/analytics',
  '/journal',
];

const STATIC_PATTERNS = [
  /\\/_next\\/static\\//,
  /\\/icons\\//,
  /\\/manifest\\.json/,
  /\\.(woff2?|ttf|otf|eot)(\\?.*)?$/,
];

const IMAGE_PATTERNS = [
  /\\.(png|jpe?g|gif|webp|svg|ico)(\\?.*)?$/,
];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) =>
      cache.add('/').catch(() => {})
    )
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith('habitflow-') && !k.endsWith(CACHE_VERSION))
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;

  if (request.method !== 'GET') return;
  if (request.headers.get('upgrade') === 'websocket') return;

  const url = request.url;
  if (PASSTHROUGH_SUBSTRINGS.some((s) => url.includes(s))) return;

  const { pathname } = new URL(url);
  if (USER_PAGE_PREFIXES.some((p) => pathname === p || pathname.startsWith(p + '/'))) return;

  if (STATIC_PATTERNS.some((p) => p.test(pathname))) {
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }

  if (IMAGE_PATTERNS.some((p) => p.test(pathname))) {
    event.respondWith(cacheFirst(request, IMAGE_CACHE));
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request, DYNAMIC_CACHE));
    return;
  }

  event.respondWith(staleWhileRevalidate(request, DYNAMIC_CACHE));
});

async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(cacheName);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return new Response('Offline', { status: 503 });
  }
}

async function networkFirst(request, cacheName) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(cacheName);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request);
    if (cached) return cached;
    const shell = await caches.match('/');
    return shell || new Response('Offline', { status: 503 });
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cache  = await caches.open(cacheName);
  const cached = await cache.match(request);
  const fetchPromise = fetch(request)
    .then((response) => {
      if (response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => cached ?? new Response('Offline', { status: 503 }));
  return cached ?? fetchPromise;
}

${firebaseConfigured ? `\
// ── Firebase Cloud Messaging ─────────────────────────────────────────────────
importScripts('${CDN}/firebase-app-compat.js');
importScripts('${CDN}/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(firebaseConfig)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function(payload) {
  var title = (payload.notification && payload.notification.title) || 'Habit Reminder';
  var body  = (payload.notification && payload.notification.body)  || '';
  self.registration.showNotification(title, {
    body:  body,
    icon:  '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    data:  { url: '/dashboard' },
  });
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  var url = (event.notification.data && event.notification.data.url) || '/dashboard';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(windowClients) {
      for (var i = 0; i < windowClients.length; i++) {
        var client = windowClients[i];
        if (client.url.indexOf(self.location.origin) !== -1 && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) return clients.openWindow(url);
    })
  );
});
` : '// Firebase not configured — push notifications disabled.'}

}
`;

writeFileSync(resolve(root, 'public', 'firebase-messaging-sw.js'), swContent);
console.log(
  'Generated public/firebase-messaging-sw.js' +
  (firebaseConfigured ? ' (with Firebase config)' : ' (Firebase not configured — push disabled)')
);
