import { NextResponse } from "next/server";

/**
 * Serves the Firebase Cloud Messaging service worker with environment
 * variables injected at request time.
 *
 * Why an API route instead of a static /public file?
 *   Next.js can only expose NEXT_PUBLIC_* vars at build time, but the service
 *   worker must be a plain .js file that cannot use module imports.  Serving
 *   it from an API route lets us inject the current env values dynamically
 *   without hardcoding secrets or requiring a rebuild when config changes.
 *
 * The `Service-Worker-Allowed: /` header allows the SW to be registered with
 * a root scope (`{ scope: '/' }`) even though it is served from /api/*.
 */
export async function GET() {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? "",
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "",
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "",
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? "",
    messagingSenderId:
      process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? "",
  };

  // Abort early if Firebase is not configured — the SW would fail silently anyway
  if (!config.apiKey || !config.projectId) {
    return new NextResponse(
      "// Firebase is not configured. Add NEXT_PUBLIC_FIREBASE_* env vars.",
      {
        headers: {
          "Content-Type": "application/javascript",
          "Cache-Control": "no-store",
        },
      }
    );
  }

  // Use Firebase v10 compat scripts — these are the only scripts officially
  // supported inside a service worker context (ESM modules are not allowed).
  const FIREBASE_VERSION = "10.7.1";
  const CDN = `https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}`;

  const swContent = `
// Firebase Cloud Messaging Service Worker
// Auto-generated by /api/firebase-messaging-sw — do not edit manually.

importScripts('${CDN}/firebase-app-compat.js');
importScripts('${CDN}/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

/**
 * Handle messages received while the app is in the background (closed or
 * minimised). FCM automatically shows the notification when a
 * notification payload is present; this handler is called for data-only
 * messages or to customise the display.
 */
messaging.onBackgroundMessage(function (payload) {
  const title =
    (payload.notification && payload.notification.title) ||
    'Habit Reminder';
  const body =
    (payload.notification && payload.notification.body) || '';

  self.registration.showNotification(title, {
    body: body,
    icon: '/favicon.ico',
    badge: '/favicon.ico',
    data: { url: '/dashboard' },
  });
});

/**
 * When the user taps the notification, navigate to the dashboard.
 */
self.addEventListener('notificationclick', function (event) {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || '/dashboard';
  event.waitUntil(
    clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function (windowClients) {
        // Focus existing tab if one is already open
        for (var i = 0; i < windowClients.length; i++) {
          var client = windowClients[i];
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            return client.focus();
          }
        }
        // Otherwise open a new tab
        if (clients.openWindow) {
          return clients.openWindow(url);
        }
      })
  );
});
`.trim();

  return new NextResponse(swContent, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Allow registration with scope '/' even though the file is under /api/
      "Service-Worker-Allowed": "/",
      // Never cache — Firebase config or VAPID key may change
      "Cache-Control": "no-store, no-cache, must-revalidate",
    },
  });
}
