import { NextResponse } from "next/server";

/**
 * Serves the single, unified HabitFlow service worker.
 *
 * Why one file instead of two?
 * A browser allows only ONE active service worker per scope. The old setup
 * registered /sw.js (caching) and then /api/firebase-messaging-sw (FCM) at the
 * same scope — the second registration would sit in "waiting" state, so
 * getToken() was called against an installing SW and silently failed.
 *
 * Serving everything from this API route lets us inject Firebase env vars at
 * request time (static files in /public can't read process.env). The
 * Service-Worker-Allowed: / header lets it control the root scope even though
 * it is served from /api/*.
 */
export async function GET() {
  const firebaseConfig = {
    apiKey:            process.env.NEXT_PUBLIC_FIREBASE_API_KEY            ?? "",
    authDomain:        process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN        ?? "",
    projectId:         process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID         ?? "",
    storageBucket:     process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET     ?? "",
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
    appId:             process.env.NEXT_PUBLIC_FIREBASE_APP_ID             ?? "",
  };

  const firebaseConfigured = !!(firebaseConfig.apiKey && firebaseConfig.projectId);
  const FIREBASE_VERSION = "10.7.1";
  const CDN = `https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}`;

  // Use string-includes checks instead of regex literals so we don't need to
  // double-escape backslashes inside the TypeScript template.
  const swContent = `
// HabitFlow — unified service worker (offline caching + Firebase Cloud Messaging)
// Auto-generated by /api/firebase-messaging-sw — do not edit directly.
// Registered with scope '/' via the Service-Worker-Allowed header.

const CACHE_VERSION = 'v4';
const STATIC_CACHE  = 'habitflow-static-'  + CACHE_VERSION;
const IMAGE_CACHE   = 'habitflow-images-'  + CACHE_VERSION;
const DYNAMIC_CACHE = 'habitflow-dynamic-' + CACHE_VERSION;

// Substring checks — requests whose URL contains any of these go straight to
// the network and are never cached.
const PASSTHROUGH_SUBSTRINGS = [
  'convex.cloud',          // Convex real-time HTTP
  'convex.site',           // Convex real-time HTTP (alt)
  'clerk.accounts.dev',    // Clerk auth domain
  'clerk.com',             // Clerk auth domain
  'accounts.tryhabitflow.com', // Clerk custom domain
  '/__clerk',              // Clerk internal routes
  '/api/',                 // All API routes (user-specific, never stale)
  '/monitoring',           // Sentry tunnel
  '/_next/webpack-hmr',    // Next.js HMR WebSocket (dev)
  '_rsc=',                 // Next.js RSC payloads
];

// Authenticated page paths — never serve from cache; always fetch fresh so a
// different account never sees the previous user's cached page.
const USER_PAGE_PREFIXES = [
  '/dashboard',
  '/profile',
  '/settings',
  '/habits',
  '/analytics',
  '/journal',
];

const STATIC_PATTERNS = [
  /\\/_next\\/static\\//,
  /\\/icons\\//,
  /\\/manifest\\.json/,
  /\\.(woff2?|ttf|otf|eot)(\\?.*)?$/,
];

const IMAGE_PATTERNS = [
  /\\.(png|jpe?g|gif|webp|svg|ico)(\\?.*)?$/,
];

// ── Install ──────────────────────────────────────────────────────────────────
self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) =>
      cache.add('/').catch(() => {})
    )
  );
});

// ── Activate ─────────────────────────────────────────────────────────────────
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith('habitflow-') && !k.endsWith(CACHE_VERSION))
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

// ── Fetch ────────────────────────────────────────────────────────────────────
self.addEventListener('fetch', (event) => {
  const { request } = event;

  if (request.method !== 'GET') return;
  if (request.headers.get('upgrade') === 'websocket') return;

  const url = request.url;
  if (PASSTHROUGH_SUBSTRINGS.some((s) => url.includes(s))) return;

  const { pathname } = new URL(url);
  if (USER_PAGE_PREFIXES.some((p) => pathname === p || pathname.startsWith(p + '/'))) return;

  if (STATIC_PATTERNS.some((p) => p.test(pathname))) {
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }

  if (IMAGE_PATTERNS.some((p) => p.test(pathname))) {
    event.respondWith(cacheFirst(request, IMAGE_CACHE));
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request, DYNAMIC_CACHE));
    return;
  }

  event.respondWith(staleWhileRevalidate(request, DYNAMIC_CACHE));
});

// ── Cache strategies ─────────────────────────────────────────────────────────
async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(cacheName);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return new Response('Offline', { status: 503 });
  }
}

async function networkFirst(request, cacheName) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(cacheName);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request);
    if (cached) return cached;
    const shell = await caches.match('/');
    return shell || new Response('Offline', { status: 503 });
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cache  = await caches.open(cacheName);
  const cached = await cache.match(request);
  const fetchPromise = fetch(request)
    .then((response) => {
      if (response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => cached ?? new Response('Offline', { status: 503 }));
  return cached ?? fetchPromise;
}

${firebaseConfigured ? `
// ── Firebase Cloud Messaging ─────────────────────────────────────────────────
importScripts('${CDN}/firebase-app-compat.js');
importScripts('${CDN}/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(firebaseConfig)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function(payload) {
  var title = (payload.notification && payload.notification.title) || 'Habit Reminder';
  var body  = (payload.notification && payload.notification.body)  || '';
  self.registration.showNotification(title, {
    body:  body,
    icon:  '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    data:  { url: '/dashboard' },
  });
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  var url = (event.notification.data && event.notification.data.url) || '/dashboard';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(windowClients) {
      for (var i = 0; i < windowClients.length; i++) {
        var client = windowClients[i];
        if (client.url.indexOf(self.location.origin) !== -1 && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) return clients.openWindow(url);
    })
  );
});
` : '// Firebase not configured — push notifications disabled.'}
`.trim();

  return new NextResponse(swContent, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Allows registration with scope '/' even though served from /api/*
      "Service-Worker-Allowed": "/",
      // Never cache — Firebase config or cache version may change on deploy
      "Cache-Control": "no-store, no-cache, must-revalidate",
    },
  });
}
